chapters = {
  "Part 0 - Introduction": [
    (1, 1, "Words of Gratitude.md"),
    (1, 1, "Important Notes on Sensitive Topics.md"),
    (1, 1, "Revolutionary Activities - Because This is Not a Theoretical Book.md"),
  ],
  "Part 1 - This Is Who We Really Are": [
    (1, 1, "Part Introduction.md"),
    (1, 1, "This is Who We Really Are.md"),
    (1, 1, "How Can a Whole Nation Embrace Generosity and Integrity.md"),
    (1, 1, "Healthy Cultures Share Three Core Spiritual Practices.md"),
    (1, 1, "Imagine If Pervasive Generosity Was Normal.md"),
    (1, 1, "Why Doesn't Everybody Live in This Beautiful Way.md"),
  ],
  "Part 2 - Why Are We So Lost": [
    (1, 1, "Part Introduction.md"),
    (1, 1, "Why Are We So Lost.md"),
    (1, 1, "Why Are People So Selfish.md"),
    (1, 1, "Why Don't More People Stand Together.md"),
    (1, 1, "Why Do People Obey Corrupt Leaders.md"),
    (1, 1, "Why Are People So Racist And Hateful.md"),
    (1, 1, "How Can a Whole Nation Embrace Awareness and Unity.md"),
    (1, 1, "Selfish Violence vs Violence-In-Service.md"),
    (1, 1, "The Endless Predation Must End.md"),
  ],
  "Part 3 - The Deepest Revolution": [
    (1, 1, "Part Introduction.md"),
    (1, 1, "The Biggest Secret in Human History.md"),
    (1, 1, "Cultivate Integrity and Bravery.md"),
    (1, 1, "Embrace the 3 Core Spiritual Practices.md"),
    (1, 1, "How Can a Whole Nation Embrace Freedom.md"),
    (1, 1, "The Deepest Revolution.md"),
  ],
  "Part 4 - Closing Notes": [
    (1, 1, "To Learn More.md"),
    (1, 1, "Bibliography.md"),
    (1, 1, "Healing Practices.md"),
    (1, 1, "Copyright.md"),
  ],
}
